/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javachess;

import javax.swing.*;
import java.awt.*;

public class App {

    private JFrame frame;
    private JPanel panel;
   
    public static void main(String[] args) {
        App app = new App();
        app.drawBoard(app.getFrame(), app.getPanel());
        app.drawPieces(app.getFrame(), app.getPanel());
    }

    public App(){
        this.frame = new JFrame("Chess Board");
        this.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frame.setSize(800, 800);
        this.frame.setLocationRelativeTo(null); 

        this.panel = new JPanel();
        this.panel.setLayout(new GridLayout(8, 8));
        this.frame.add(panel);
    }

    public  JFrame getFrame(){
        return frame;
    }

    public  JPanel getPanel(){
        return panel;
    }

    public  void drawBoard(JFrame frame, JPanel panel){
        
        Color dark = new Color(125, 135, 150);
        Color light = new Color(233, 236, 239);

        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                JPanel square = new JPanel();
                if ((i + j) % 2 == 0) {
                    square.setBackground(light);
                } else {
                    square.setBackground(dark);
                }
                panel.add(square);
            }
        }

        frame.setVisible(true);
    }

    public  void drawPieces(JFrame frame,JPanel panel){
        String[] pieces = {
            "♜", "♞", "♝", "♛", "♚", "♝", "♞", "♜",
            "♟", "♟", "♟", "♟", "♟", "♟", "♟", "♟",
            " ", " ", " ", " ", " ", " ", " ", " ",
            " ", " ", " ", " ", " ", " ", " ", " ",
            " ", " ", " ", " ", " ", " ", " ", " ",
            " ", " ", " ", " ", " ", " ", " ", " ",
            "♙", "♙", "♙", "♙", "♙", "♙", "♙", "♙",
            "♖", "♘", "♗", "♕", "♔", "♗", "♘", "♖"
        };

        panel = (JPanel) frame.getContentPane().getComponent(0);
        Component[] squares = panel.getComponents();

        for (int i = 0; i < pieces.length; i++) {
            JLabel pieceLabel = new JLabel(pieces[i]);
            pieceLabel.setFont(new Font("Arial", Font.PLAIN, 60));
            ((Container) squares[i]).add(pieceLabel);
        }
    }

    public void handleEvents(){
    }

    
}